# Use uma imagem oficial do Node.js
FROM node:14.21.3

# Crie e defina o diretório de trabalho no contêiner
WORKDIR /app

# Copie o arquivo package.json e package-lock.json para o diretório de trabalho
COPY frontend/package*.json ./

# Instale as dependências
RUN npm install

# Copie todo o conteúdo do diretório frontend para o diretório de trabalho
COPY frontend .

# Execute o comando de teste
CMD ["npm", "test"]
