# Use a imagem oficial do Node.js v18
FROM node:18

# Defina o diretório de trabalho como o diretório 'frontend'
WORKDIR /frontend

# Copie o arquivo package.json e package-lock.json para o contêiner
COPY frontend/package*.json .

# Instale as dependências do projeto
RUN npm install

# Copie todo o conteúdo do diretório 'frontend' para o contêiner
COPY . .

# Comando padrão para executar os testes
CMD ["npm", "test"]
