version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:5173"
    # outras configurações específicas do frontend

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "3333:3333"
    # outras configurações específicas do backend
