version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "5173:5173"
    # outras configurações específicas do frontend

  backend:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "3333:3333"
    # outras configurações específicas do backend

  prisma-studio:
    image: dockerfile  # Use a mesma imagem do backend
    command: ["npx", "prisma", "studio"]
    ports:
      - "5555:5555"  # Porta em que o Prisma Studio será acessível
    depends_on:
      - backend
