FROM node:16-alpine

WORKDIR /tests

# Copie os arquivos de teste e configurações
COPY ./frontend .

# Atualizar npm para a versão mais recente
RUN npm install -g npm@10.4.0

# Instale as dependências de teste
RUN npm install

# Comando padrão para executar os testes
CMD ["npm", "test"]
