version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    command: "npm test"
    ports:
      - "5173:5173"

    # outras configurações específicas do frontend

  #frontend-test:
    #build:
      #context: .
      #dockerfile: Dockerfile.tests
    #command: npm test
    
    # outras configurações específicas do frontend


  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    command: npm run dev:server
    ports:
      - "3333:3333"
    # outras configurações específicas do backend
